[build]
  base = "frontend"
  command = "npm ci && npm run build:prod"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200